.Linux Container Namespace I
****
== 概述

有没有想过 Linux Container是如何工作的？？？

目前，Docker 是最流行、最流行的容器实现之一。

容器在同一操作系统内核之上运行，但将容器内运行的应用程序进程彼此隔离。容器背后的秘密武器之一是命名空间。

命名空间抽象了全局系统资源，例如主机名、用户 ID、组 ID、进程 ID、网络端口等，对于进程（在命名空间内）来说，就好像它们拥有自己的全局系统资源的隔离实例一样。命名空间的主要目标之一是支持容器的实现（轻量级虚拟化）。

目前，Linux 中有6种类型的命名空间 - IPC、 Network、Mount、PID、 User和UTS。

以下是每个命名空间的简要说明：

IPC :: 此命名空间隔离某些进程间通信 (IPC) 资源，即消息队列、信号量和共享内存

Network :: 此命名空间提供与网络相关的系统资源的隔离，例如网络设备、IP 地址、IP 路由表、/proc/net 目录、端口号等

Mount :: 此命名空间隔离一组进程看到的文件系统挂载点集。不同挂载命名空间中的进程可以具有不同的文件系统层次结构视图

PID ::这个命名空间隔离了进程ID号空间。这允许不同 PID 命名空间中的进程具有相同的 PID

User :: 该命名空间隔离了用户和组 ID 号空间，这样，进程的用户和组 ID 在用户命名空间内部和外部可以不同

UTS :: 该命名空间隔离了两个系统标识符——主机名和域名。对于容器来说，UTS命名空间允许每个容器拥有自己的主机名和NIS域名

对于本文中的演示，我们将使用unshare Linux 命令以及使用golang实现、构建和执行一个简单的容器。

== 安装和设置

安装在基于Ubuntu 18.04 LTS的 Linux 桌面上。

我们需要两个命令newuidmap和newgidmap 来演示用户命名空间。为此，我们需要安装 uidmap包。

要安装软件包uidmap，请执行以下命令：
[source,bash]
$ sudo apt install -y uidmap

接下来，我们需要brctl命令来创建桥接 网络接口。为此，我们需要安装包bridge-utils。

要安装包bridge-utils，请执行以下命令：
[source,bash]
$ apt install -y bridge-utils

要使用go编程语言开发、构建和执行简单容器，我们需要安装golang包。

要检查可安装的golang版本，请执行以下命令：

[source,bash]
$ apt-cache police golang

以下是典型的输出：

[source]
.output.2
----
golang:
Installed: (none)
Candidate: 2:1.13~1ubuntu1ppa1~bionic
Version table:
*** 2:1.13~1ubuntu1ppa1~bionic 500
500 http://ppa.launchpad.net/hnakamur/golang-1.13/ubuntu bionic/main amd64 Packages
500 http://ppa.launchpad.net/hnakamur/golang-1.13/ubuntu bionic/main i386 Packages
100 /var/lib/dpkg/status
2:1.10~4ubuntu1 500
500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
----

[source,bash]
$ apt install -y golang

上述安装过程从官方 Ubuntu 存储库安装golang 。

通过执行以下命令创建一个用于开发、构建和运行go程序的目录：

[source, bash]
$ mkdir $HOME/projects/go
$ export GOPATH=$HOME/projects/go

我们需要netlink上流行的go软件包之一来 进行网络连接。

要下载go包，请执行以下命令：

[source,bash]
$ go get github.com/vishvananda/netlink

打开两个终端窗口 - 我们将它们分别称为TA 和TB。TB是我们演示简单容器的地方。

我们需要下载一个最小的根文件系统（rootfs），它将用作简单容器的基础映像。为了进行演示，我们将选择撰写本文时最新的 link:https://cdimage.ubuntu.com/ubuntu-base/releases/18.04.4/release/ubuntu-base-18.04.5-base-amd64.tar.gz[ Ubuntu Base 18.04.5 LTS]
我们假设最新的 Ubuntu Base 已下载到目录 `$HOME/Downloads`。

== Namespace实践

=== UTS Namespace
unshare命令使用与父进程隔离的指定命名空间来执行指定的程序。

要显示unshare命令的选项，请在TA中执行以下命令 ：

[source,bash]
$ unshare -h

以下是典型的输出：

[source]
.output.3
----
Usage:
 unshare [options] [<program> [<argument>...]]

Run a program with some namespaces unshared from the parent.

Options:
-m, --mount[=<file>]      unshare mounts namespace
-u, --uts[=<file>]        unshare UTS namespace (hostname etc)
-i, --ipc[=<file>]        unshare System V IPC namespace
-n, --net[=<file>]        unshare network namespace
-p, --pid[=<file>]        unshare pid namespace
-U, --user[=<file>]       unshare user namespace
-C, --cgroup[=<file>]     unshare cgroup namespace
-f, --fork                fork before launching <program>
--mount-proc[=<dir>]  mount proc filesystem first (implies --mount)
-r, --map-root-user       map current user to root (implies --user)
--propagation slave|shared|private|unchanged
modify mount propagation in mount namespace
-s, --setgroups allow|deny  control the setgroups syscall in user namespaces

 -h, --help                display this help
 -V, --version             display version
----

每个进程（带有 [PID]）都与其关联一个子目录/proc/[PID]/ns，其中包含每个命名空间的一个条目。

要列出与进程关联的所有命名空间，请在TA中执行以下命令 ：

[source, bash]
$ ls -l /proc/$$/ns

以下是典型的输出：

[source]
.output.4
----
total 0
lrwxrwxrwx 1 alice alice 0 Mar  7 12:17 cgroup -> 'cgroup:[4026531835]'
lrwxrwxrwx 1 alice alice 0 Mar  7 12:17 ipc -> 'ipc:[4026531839]'
lrwxrwxrwx 1 alice alice 0 Mar  7 12:17 mnt -> 'mnt:[4026531840]'
lrwxrwxrwx 1 alice alice 0 Mar  7 12:17 net -> 'net:[4026531993]'
lrwxrwxrwx 1 alice alice 0 Mar  7 12:17 pid -> 'pid:[4026531836]'
lrwxrwxrwx 1 alice alice 0 Mar  7 20:41 pid_for_children -> 'pid:[4026531836]'
lrwxrwxrwx 1 alice alice 0 Mar  7 12:17 user -> 'user:[4026531837]'
lrwxrwxrwx 1 alice alice 0 Mar  7 12:17 uts -> 'uts:[4026531838]'
----
要启动主机名与父主机名隔离的简单容器，请在TB中执行以下命令 ：

[source,bash]
$ unshare -u /bin/sh

-u选项启用UTS命名空间。

命令提示符将更改为#。

要检查简单容器的PID ，请在 TB中执行以下命令：
[source, bash]
----
$ echo $$
----

以下是典型的输出：

[source]
.output.5
18872

要列出与简单容器关联的所有命名空间，请在TB中执行以下命令：

[source, bash]
$ ls -l /proc/$$/ns

以下是典型的输出：

[source]
.output.6
----
total 0
lrwxrwxrwx 1 root root 0 Mar  7 12:36 cgroup -> 'cgroup:[4026531835]'
lrwxrwxrwx 1 root root 0 Mar  7 12:36 ipc -> 'ipc:[4026531839]'
lrwxrwxrwx 1 root root 0 Mar  7 12:36 mnt -> 'mnt:[4026531840]'
lrwxrwxrwx 1 root root 0 Mar  7 12:36 net -> 'net:[4026531993]'
lrwxrwxrwx 1 root root 0 Mar  7 12:36 pid -> 'pid:[4026531836]'
lrwxrwxrwx 1 root root 0 Mar  7 12:36 pid_for_children -> 'pid:[4026531836]'
lrwxrwxrwx 1 root root 0 Mar  7 12:36 user -> 'user:[4026531837]'
lrwxrwxrwx 1 root root 0 Mar  7 12:36 uts -> 'uts:[4026533064]'
----
要更改简单容器的主机名，请在TB中执行以下命令：

[source,bash]
$ hostname leopard

要显示父主机的主机名，请在TA中执行以下命令：

[source, bash]
$ hostname

以下是典型的输出：

[source]
.output.7
polarsparc

要显示简单容器的主机名，请在TB中执行以下命令：

[source,bash]
$ hostname

以下是典型的输出：

[source]
.output.8
leopard

这向我们表明，我们已经将简单容器的主机名与父主机名隔离开来。

要退出简单容器，请在TB中执行以下命令：

[source,bash]
$ exit

接下来，我们将使用以下 go程序来模拟上述UTS命名空间隔离：

[source,go]
----
package main

import (
	"log"
	"os"
	"os/exec"
	"syscall"
)

func execContainerShell() {
	log.Printf("Ready to exec container shell ...\n")

	if err := syscall.Sethostname([]byte("leopard")); err != nil {
		panic(err)
	}

	const sh = "/bin/sh"

	env := os.Environ()
	env = append(env, "PS1=-> ")

	if err := syscall.Exec(sh, []string{""}, env); err != nil {
		panic(err)
	}
}

func main() {
	log.Printf("Starting process %s with args: %v\n", os.Args[0], os.Args)

	const clone = "CLONE"

	if len(os.Args) > 1 && os.Args[1] == clone {
		execContainerShell()
	}

	log.Printf("Ready to run command ...\n")

	cmd := exec.Command(os.Args[0], []string{clone}...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Cloneflags: syscall.CLONE_NEWUTS,
	}

	if err := cmd.Run(); err != nil {
		panic(err)
	}
}

----
exec包中的Command函数允许使用提供的参数（第二个参数）运行指定的命令（第一个参数）。它返回Cmd结构的实例。

可以在返回的Cmd实例上设置标准输入 ( os.Stdin )、标准输出 os.Stdout、标准错误os.Stderr以及一些操作系统特定的属性。在本例中，我们指定 syscall.CLONE_NEWUTS OS 属性来指示该命令在新的UTS命名空间中运行 。

重要提示：当主进程启动时，它会在新的命名空间中内部生成另一个主进程（带有CLONE参数）。正是这个生成的主进程（在新命名空间中运行）通过调用函数 execContainerShell与 shell 命令重叠（syscall.Exec ） 。

通过在TB中执行以下命令来 创建并更改目录$GOPATH/uts：

[source,bash]
----
$ mkdir -p $GOPATH/uts

$ cd $GOPATH/uts
----

将上述代码复制到当前目录下的程序文件main.go中。

要编译程序文件main.go ，请在 TB中执行以下命令：

[source,bash]
$ go build main.go

要运行程序main ，请在TB中执行以下命令：

[source,bash]
$ ./main

以下是典型的输出：
[source]
.output.9
2020/03/07 12:49:11 Starting process ./main with args: [./main]
2020/03/07 12:49:11 Ready to run command ...
2020/03/07 12:49:11 Starting process ./main with args: [./main CLONE]
2020/03/07 12:49:11 Ready to exec container shell ...
->

命令提示符将更改为->。

要显示简单容器的主机名，请在TB中执行以下命令：

[source,bash]
-> hostname

以下是典型的输出：

[source]
.output.10
leopard

要退出简单容器，请在TB中执行以下命令：

[source]
-> exit

成功 ！！！我们已经使用unshare命令和一个简单的go程序演示了UTS命名空间。



=== User Namespace

让我们将User命名空间置于UTS命名空间之上。

要启动一个简单容器，其用户/组 ID 以及主机名与父命名空间隔离，请在TB中执行以下命令：

[source,bash]
$ unshare -uU /bin/sh

-U选项启用用户命名空间。

要显示新命名空间中的用户 ID 和组 ID，请在TB中执行以下命令：

[source,bash]
$ id

以下是典型的输出：

[source]
.output.11
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)

创建用户命名空间后，它启动时不会将新命名空间中的用户/组 ID 映射到父用户/组 ID。未映射的用户/组 ID 被分配溢出用户/组 ID 的默认值。溢出用户 ID 的默认值是从 /proc/sys/kernel/overflowuid中读取的（即 65534）。同样，溢出组 ID 的默认值是从/proc/sys/kernel/overflowgid中读取的（即 65534）。

要修复用户/组 ID 到父用户/组 ID 的映射，请通过在TB中执行以下命令退出简单容器：

[source,bash]
$ exit

要重新启动简单容器，并将当前有效用户/组 ID 映射到新命名空间中的超级用户用户/组 ID，请在TB中执行以下命令：

[source,bash]
$ unshare -uUr /bin/sh

-r选项允许将新命名空间中的用户/组 ID 映射到父命名空间用户/组 ID。

命令提示符将更改为#。

要显示新命名空间中的用户 ID 和组 ID，请在TB中执行以下命令：

[source,bash]
＃ id

以下是典型的输出：

[source]
.output.12
uid=0(root) gid=0(root) groups=0(root)

要列出与简单容器关联的所有命名空间，请在TB中执行以下命令：

[source,bash]
----
# ls -l /proc/$$/ns
----

以下是典型的输出：

[source]
.output.13
----
total 0
lrwxrwxrwx 1 root root 0 Mar 7 13:09 cgroup -> 'cgroup:[4026531835]'
lrwxrwxrwx 1 root root 0 Mar 7 13:09 ipc -> 'ipc:[4026531839]'
lrwxrwxrwx 1 root root 0 Mar 7 13:09 mnt -> 'mnt:[4026531840]'
lrwxrwxrwx 1 root root 0 Mar 7 13:09 net -> 'net:[4026531993]'
lrwxrwxrwx 1 root root 0 Mar 7 13:09 pid -> 'pid:[4026531836]'
lrwxrwxrwx 1 root root 0 Mar 7 13:09 pid_for_children -> 'pid:[4026531836]'
lrwxrwxrwx 1 root root 0 Mar 7 13:09 user -> 'user:[4026532892]'
lrwxrwxrwx 1 root root 0 Mar 7 13:09 uts -> 'uts:[4026533401]'
----
比较 .output.12 和 .output.3，我们看到uts命名空间和user命名空间都发生了变化，这是预期的且正确的。

要退出简单容器，请在TB中执行以下命令：

[source]
＃ exit

接下来，我们将使用以下go程序来模拟上述UTS和用户命名空间隔离：

[source,go]
----
package main

import (
	"log"
	"os"
	"os/exec"
	"syscall"
)

func execContainerShell() {
	log.Printf("Ready to exec container shell ...\n")

	if err := syscall.Sethostname([]byte("leopard")); err != nil {
		panic(err)
	}

	const sh = "/bin/sh"

	env := os.Environ()
	env = append(env, "PS1=-> ")

	if err := syscall.Exec(sh, []string{""}, env); err != nil {
		panic(err)
	}
}

func main() {
	log.Printf("Starting process %s with args: %v\n", os.Args[0], os.Args)

	const clone = "CLONE"

	if len(os.Args) > 1 && os.Args[1] == clone {
		execContainerShell()
	}

	log.Printf("Ready to run command ...\n")

	cmd := exec.Command(os.Args[0], []string{clone}...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Cloneflags: syscall.CLONE_NEWUTS,
	}

	if err := cmd.Run(); err != nil {
		panic(err)
	}
}

----
如前所述，Command函数返回Cmd结构的实例 。

在此示例中，我们指定附加的syscall.CLONE_NEWUSER OS 属性来指示该命令在新的用户命名空间中运行。

此外，我们将用户 ID 映射UidMappings设置为syscall.SysProcIDMap结构体条目的数组 ，每个结构体条目包含容器中的用户 ID ( ContainerID ) 到主机命名空间中的用户 ID ( HostID ) 的映射。在本例中，我们将容器中的root用户 ID 0映射到主机命名空间的root用户 ID 0 。同样，我们设置组ID映射GidMappings

通过在TB中执行以下命令来 创建并更改目录$GOPATH/user：

[source,bash]
----
$ mkdir -p $GOPATH/user

$ cd $GOPATH/user
----

将上述代码复制到当前目录下的程序文件main.go中。

要编译程序文件main.go ，请在 TB中执行以下命令：

[source,bash]
$ go build main.go

要运行程序main ，请在TB中执行以下命令：

[source,bash]
$ ./main

以下是典型的输出：

[source]
.output.14
----
2020/03/07 13:17:02 Starting process ./main with args: [./main]
2020/03/07 13:17:02 Ready to run command ...
2020/03/07 13:17:02 Starting process ./main with args: [./main CLONE]
2020/03/07 13:17:02 Ready to exec container shell ...
->
----
命令提示符将更改为->。

要显示新命名空间中的用户 ID 和组 ID，请在TB中执行以下命令：

[source,bash]
-> id

以下是典型的输出：

[source]
ouput.15
uid=0(root) gid=0(root) groups=0(root)

要列出与简单容器关联的所有命名空间，请在TB中执行以下命令：

[source]
-> ls -l /proc/$$/ns

以下是典型的输出：

[source]
.output.16
----
total 0
lrwxrwxrwx 1 root root 0 Mar 13 21:17 cgroup -> 'cgroup:[4026531835]'
lrwxrwxrwx 1 root root 0 Mar 13 21:17 ipc -> 'ipc:[4026531839]'
lrwxrwxrwx 1 root root 0 Mar 13 21:17 mnt -> 'mnt:[4026531840]'
lrwxrwxrwx 1 root root 0 Mar 13 21:17 net -> 'net:[4026531993]'
lrwxrwxrwx 1 root root 0 Mar 13 21:17 pid -> 'pid:[4026531836]'
lrwxrwxrwx 1 root root 0 Mar 13 21:17 pid_for_children -> 'pid:[4026531836]'
lrwxrwxrwx 1 root root 0 Mar 13 21:17 user -> 'user:[4026532666]'
lrwxrwxrwx 1 root root 0 Mar 13 21:17 uts -> 'uts:[4026532723]'
----
要显示简单容器的主机名，请在TB中执行以下命令：

[source,bash]
-> hostname

以下是典型的输出：

[source]
.output.17
leopard

要退出简单容器，请在TB中执行以下命令：

[source,bash]
-> exit

成功 ！！！我们使用unshare命令和一个简单的 go程序演示了组合的UTS和 User命名空间。

=== PID Namespace

现在让我们将PID命名空间置于User命名空间和UTS命名空间之上。

要启动一个简单容器，其进程 ID 以及用户/组 ID 和主机名与父命名空间隔离，请在TB中执行以下命令：

[source,bash]
$ unshare -uUrpf --mount-proc /bin/sh

-p选项启用PID命名空间。

-f选项允许在新命名空间中生成（或分叉）新进程。

--mount -proc选项将proc文件系统作为私有挂载安装在新命名空间中的/proc处。这意味着 /proc伪目录仅显示有关该PID 命名空间内进程的信息。

.注意
IMPORTANT: 确保选项-f是 * SPECIFIED *。否则会遇到如下错误：
/bin/sh: 4: Cannot fork

命令提示符将更改为#。

要显示新命名空间中的所有进程，请在TB中执行以下命令：

[source,bash]
----
# ps-fu
----

以下是典型的输出：

[source]
.output.18
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4628   880 pts/1    S    09:08   0:00 /bin/sh
root         6  0.0  0.0  37368  3340 pts/1    R+   09:12   0:00 ps -fu

要显示父命名空间中的所有进程，请在TA中执行以下命令：

[source,bash]
$ ps-fu

以下是典型的输出：

[source]
.output.19
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
polarsparc  8695  0.0  0.0  22840  5424 pts/1    Ss   08:43   0:00 bash
polarsparc  8681  0.0  0.0  22708  5096 pts/0    Ss   08:43   0:00 bash
polarsparc  9635  0.0  0.0  37368  3364 pts/0    R+   09:12   0:00  \_ ps -fu

比较 .output.17 和 .output.18，我们看到新命名空间和父命名空间之间的隔离，这是预期的且正确的。

要退出简单容器，请在TB中执行以下命令：

[source]
＃ exit

接下来，我们将使用以下go程序来模拟上述UTS、User和 PID命名空间隔离：

[source,go]
----
package main

import (
	"log"
	"os"
	"os/exec"
	"syscall"
)

func execContainerShell() {
	log.Printf("Ready to exec container shell ...\n")

	if err := syscall.Sethostname([]byte("leopard")); err != nil {
		panic(err)
	}

	if err := syscall.Mount("proc", "/proc", "proc", 0, ""); err != nil {
		panic(err)
	}

	const sh = "/bin/sh"

	env := os.Environ()
	env = append(env, "PS1=-> ")

	if err := syscall.Exec(sh, []string{""}, env); err != nil {
		panic(err)
	}
}

func main() {
	log.Printf("Starting process %s with args: %v\n", os.Args[0], os.Args)

	const clone = "CLONE"

	if len(os.Args) > 1 && os.Args[1] == clone {
		execContainerShell()
		os.Exit(0)
	}

	log.Printf("Ready to run command ...\n")

	cmd := exec.Command(os.Args[0], []string{clone}...)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Cloneflags: syscall.CLONE_NEWUTS | syscall.CLONE_NEWUSER | syscall.CLONE_NEWNS | syscall.CLONE_NEWPID,
		UidMappings: []syscall.SysProcIDMap{
			{ContainerID: 0, HostID: 0, Size: 1},
		},
		GidMappings: []syscall.SysProcIDMap{
			{ContainerID: 0, HostID: 0, Size: 1},
		},
	}

	if err := cmd.Run(); err != nil {
		panic(err)
	}
}

----
如前所述，Command函数返回Cmd结构的实例 。

在此示例中，我们指定额外的syscall.CLONE_NEWNS和 syscall.CLONE_NEWPID OS 属性来指示命令在新的 PID命名空间中运行。

通过在TB中执行以下命令来 创建并更改目录$GOPATH/pid：

[source,bash]
----
$ mkdir -p $GOPATH/pid

$ cd $GOPATH/pid
----

将上述代码复制到当前目录下的程序文件main.go中。

要编译程序文件main.go ，请在 TB中执行以下命令：

[source,bash]
$ go build main.go

要运行程序main ，请在TB中执行以下命令：

[source,bash]
$ ./main

以下是典型的输出：

[source]
.output.20
2020/03/07 13:38:02 Starting process ./main with args: [./main]
2020/03/07 13:38:02 Ready to run command ...
2020/03/07 13:38:02 Starting process ./main with args: [./main CLONE]
2020/03/07 13:38:02 Ready to exec container shell ...
->

命令提示符将更改为->。

要显示简单容器的主机名，请在TB中执行以下命令：

[source,bash]
-> hostname

以下是典型的输出：

[source]
ouput.21
leopard

要显示新命名空间中的用户 ID 和组 ID，请在TB中执行以下命令：

[source]
-> id

以下是典型的输出：

[source]
ouput.22
uid=0(root) gid=0(root) groups=0(root)

要显示简单容器中的所有进程，请在TB中执行以下命令：

[source]
-> ps -fu

以下是典型的输出：

[source]
.output.23
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   4628   776 pts/1    S    09:41   0:00
root         6  0.0  0.0  37368  3400 pts/1    R+   09:41   0:00 ps -fu

要列出与简单容器关联的所有命名空间，请在TB中执行以下命令：

[source]
-> ls -l /proc/$$/ns

以下是典型的输出：

[source]
.output.24
total 0
lrwxrwxrwx 1 root root 0 Mar 14 09:44 cgroup -> 'cgroup:[4026531835]'
lrwxrwxrwx 1 root root 0 Mar 14 09:44 ipc -> 'ipc:[4026531839]'
lrwxrwxrwx 1 root root 0 Mar 14 09:44 mnt -> 'mnt:[4026532366]'
lrwxrwxrwx 1 root root 0 Mar 14 09:44 net -> 'net:[4026531993]'
lrwxrwxrwx 1 root root 0 Mar 14 09:44 pid -> 'pid:[4026532368]'
lrwxrwxrwx 1 root root 0 Mar 14 09:44 pid_for_children -> 'pid:[4026532368]'
lrwxrwxrwx 1 root root 0 Mar 14 09:44 user -> 'user:[4026532365]'
lrwxrwxrwx 1 root root 0 Mar 14 09:44 uts -> 'uts:[4026532367]'

要退出简单容器，请在TB中执行以下命令：

[source]
-> exit

成功 ！！！我们使用 unshare命令和一个简单的go程序演示了组合的UTS、 User和PID命名空间。

=== Mount Namespace

现在，我们将设置最小的 Ubuntu Base 映像，以便在/tmp目录中的新命名空间中使用 。

要创建基础映像并将其复制到/tmp中的目录，请在TA中执行以下命令：

[source,bash]
----
$ mkdir -p /tmp/rootfs/.old_root

$ tar -xvf $HOME/Downloads/ubuntu-base-18.04.5-base-amd64.tar.gz --directory /tmp/rootfs

$ cd/tmp
----

现在让我们将Mount命名空间置于User、UTS和PID命名空间之上。

要启动一个简单容器，其挂载点以及进程 ID、用户/组 ID 和主机名与父命名空间隔离，请在TB中执行以下命令：

[source,bash]
$ unshare -uUrpfm --mount-proc /bin/sh

-m选项启用Mount命名空间。

命令提示符将更改为#。

要列出父命名空间中的所有挂载点，请在TA中执行以下命令：

[source,bash]
$ cat /proc/mounts | sort

以下是典型的输出：
[source]
.output.25
----
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sdb1 /home ext4 rw,relatime,data=ordered 0 0
/dev/sdc1 /home/data ext4 rw,relatime,data=ordered 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=25,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=28210 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=3293620k,mode=755 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=3293616k,mode=700,uid=1000,gid=1000 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=16402556k,nr_inodes=4100639,mode=755 0 0
----
现在，让我们通过在TB中执行以下命令来列出新命名空间中的所有挂载点：

[source,bash]
----
# cat /proc/mounts | sort
----

以下是典型的输出：

[source]
----
.output.25
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/rdma cgroup rw,nosuid,nodev,noexec,relatime,rdma 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
cgroup /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
/dev/sdb1 /home ext4 rw,relatime,data=ordered 0 0
/dev/sdc1 /home/data ext4 rw,relatime,data=ordered 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime,pagesize=2M 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=25,pgrp=0,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=28210 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=3293620k,mode=755 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=3293616k,mode=700,uid=1000,gid=1000 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=16402556k,nr_inodes=4100639,mode=755 0 0
----
比较 .output.25 和 .output.24，我们看到proc的一个区别。创建新的 Mount命名空间时，新命名空间的挂载点是父命名空间中挂载点的副本。

我们现在将演示对新命名空间的任何更改都不会影响父命名空间。

要使挂载点/（及其递归子项）成为新名称空间的私有挂载点，请在TB中执行以下命令：

[source,bash]
----
# mount --make-rprivate /
----

要将挂载点rootfs/递归绑定到新命名空间中的rootfs/ ，请在TB中执行以下命令：

[source,bash]
----
# mount --rbind rootfs/rootfs/
----

我们需要新命名空间中的proc文件系统来更改挂载。要将 /proc作为新命名空间中的 proc 文件系统proc挂载，请在TB中执行以下命令：

[source,bash]
----
# mount -t proc proc rootfs/proc
----

接下来，我们需要将rootfs/作为新命名空间中的根文件系统，并使用pivot_root命令将父根文件系统移动到rootfs/.old_root 。为此，请在TB中执行以下命令：

[source,bash]
----
# pivot_root rootfs/ rootfs/.old_root

# cd /
----

要列出父命名空间中/下的所有文件，请在TA中执行以下命令 ：

[source,bash]
$ ls -l /

以下是典型的输出：

[source]
.output.26
total 96
drwxr-xr-x   2 root root  4096 Mar  1 10:58 bin
drwxr-xr-x   3 root root  4096 Mar 16 21:15 boot
drwxr-xr-x   2 root root  4096 Sep 13  2019 cdrom
drwxr-xr-x  22 root root  4560 Mar 21 06:59 dev
drwxr-xr-x 163 root root 12288 Mar 20 10:01 etc
drwxr-xr-x   5 root root  4096 Sep 13  2019 home
lrwxrwxrwx   1 root root    33 Mar 16 21:15 initrd.img -> boot/initrd.img-4.15.0-91-generic
lrwxrwxrwx   1 root root    33 Feb 17 14:08 initrd.img.old -> boot/initrd.img-4.15.0-88-generic
drwxr-xr-x  25 root root  4096 Mar 16 13:37 lib
drwxr-xr-x   2 root root  4096 Jul 29  2019 lib64
drwx------   2 root root 16384 Sep 13  2019 lost+found
drwxr-xr-x   3 root root  4096 Nov 10 13:00 media
drwxr-xr-x   2 root root  4096 Jul 29  2019 mnt
drwxr-xr-x   7 root root  4096 Mar 13 08:04 opt
dr-xr-xr-x 328 root root     0 Mar 21 06:59 proc
drwx------   9 root root  4096 Feb 23 13:25 root
drwxr-xr-x  36 root root  1140 Mar 21 07:04 run
drwxr-xr-x   2 root root 12288 Mar 16 13:37 sbin
drwxr-xr-x   2 root root  4096 Jul 29  2019 srv
dr-xr-xr-x  13 root root     0 Mar 21 06:59 sys
drwxrwxrwt  20 root root  4096 Mar 21 11:10 tmp
drwxr-xr-x  11 root root  4096 Jul 29  2019 usr
drwxr-xr-x  11 root root  4096 Jul 29  2019 var
lrwxrwxrwx   1 root root    30 Mar 16 21:15 vmlinuz -> boot/vmlinuz-4.15.0-91-generic
lrwxrwxrwx   1 root root    30 Feb 17 14:08 vmlinuz.old -> boot/vmlinuz-4.15.0-88-generic

要列出新命名空间中/下的所有文件，请在TB中执行以下命令 ：

[source,bash]
----
# ls -l /
----

以下是典型的输出：

[source]
.output.27
total 72
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:24 bin
drwxr-xr-x   2 nobody nogroup 4096 Apr 24  2018 boot
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:24 dev
drwxr-xr-x  29 nobody nogroup 4096 Feb  3 20:24 etc
drwxr-xr-x   2 nobody nogroup 4096 Apr 24  2018 home
drwxr-xr-x   8 nobody nogroup 4096 May 23  2017 lib
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:23 lib64
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:23 media
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:23 mnt
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:23 opt
dr-xr-xr-x 328 root   root       0 Mar 21 14:10 proc
drwx------   2 nobody nogroup 4096 Feb  3 20:24 root
drwxr-xr-x   4 nobody nogroup 4096 Feb  3 20:23 run
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:24 sbin
drwxr-xr-x   2 nobody nogroup 4096 Feb  3 20:23 srv
drwxr-xr-x   2 nobody nogroup 4096 Apr 24  2018 sys
drwxrwxr-x   2 nobody nogroup 4096 Feb  3 20:24 tmp
drwxr-xr-x  10 nobody nogroup 4096 Feb  3 20:23 usr
drwxr-xr-x  11 nobody nogroup 4096 Feb  3 20:24 var

比较 .output.26 和 .output.27，我们看到根文件系统完全不同。

要将/tmp作为新命名空间中的临时文件系统tmpfs挂载，请在TB中执行以下命令：

[source,bash]
----
# mount -t tmpfs tmpfs /tmp
----

要在新命名空间的目录/tmp中创建文本文件/tmp/leopard.txt ，请在TB 中执行以下命令：

[source,bash]
----
# echo 'leopard' > /tmp/leopard.txt
----

要列出新命名空间中文件/tmp/leopard.txt的属性，请在TB中执行以下命令：

[source,bash]
----
# ls -l /tmp/leopard.txt
----

以下是典型的输出：

[source]
.output.28
-rw-r--r-- 1 root root 7 Mar 14 22:05 /tmp/leopard.txt

要列出父命名空间中文件/tmp/leopard.txt的属性，请在TA中执行以下命令：

[source,bash]
$ ls -l /tmp/leopard.txt

以下是典型的输出：

[source]
.output.29
ls: cannot access '/tmp/leopard.txt': No such file or directory

最后，要从新命名空间中完全删除父根文件系统rootfs/.old_root ，请在TB中执行以下命令：

[source,bash]
----
# mount --make-rprivate /.old_root

# umount -l /.old_root
----

要列出新命名空间中的所有挂载点，请在TB中执行以下命令 ：

[source,bash]
----
# cat /proc/mounts | sort
----

以下是典型的输出：

[source]
.output.30
/dev/sda1 / ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
proc /proc proc rw,relatime 0 0
tmpfs /tmp tmpfs rw,relatime 0 0

要退出新命名空间，请在TB中执行以下命令：

[source,bash]
＃ exit

成功 ！！！我们已经使用unshare命令演示了组合的UTS、 User、PID和Mount命名空间。

****